# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 933aa7a5f5659213dbbdf9bcac8c1accb4f4ff91395785e199a7142a432fb44ef66bcb79111c1f800730e00b4991b04df86966192d1485a1ef1d7db5d4ea58cc

test:
  secret_key_base: 3312d86882b086d5ab56ff92bf1aad851b4722e8f5e2307c85e2448490c23452aad2e726bed9d17f09d8fac1380aff35fa836f7ad325e40a3095b99f53d49e39

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
